// GENERATED by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
	id: "dsh-schedule-later",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		var react = require("react");
		var react_jsx_runtime = react;
// Client-layer core for dsh-schedule-later (browser side, framework-free and
// testable in Node). The lib/client.js bundle wraps this with React/slots.

/** Media query marking the mobile layout (FIX 5). */
const MOBILE_QUERY = '(max-width: 480px)';

/**
 * Grace window during which a freshly POSTed task survives a refresh whose
 * server snapshot was taken BEFORE the task existed (FIX 4 race).
 */
const LOCAL_ADD_GRACE_MS = 10_000;

/** Safe matchMedia probe: never throws, false when unavailable. */
function isMobileViewport(matchMedia) {
  try {
    if (typeof matchMedia !== 'function') return false;
    return !!matchMedia(MOBILE_QUERY)?.matches;
  } catch {
    return false;
  }
}

/** Sort a task list by sendAt ascending (display order). */
function sortTasks(tasks) {
  return [...(tasks || [])].sort((a, b) => (a.sendAt || 0) - (b.sendAt || 0));
}

/**
 * Collapse rule for the dock (FIX 2):
 *  - default (desktop): >1 entry → show ONLY the soonest (sendAt-min) entry
 *    plus a "N more scheduled ⌄" summary toggle; ≤1 entry → expanded.
 *  - default (mobile): fully collapsed (summary only).
 *  - user 'expanded' → all entries; user 'collapsed' → nothing but the
 *    summary (manual collapse-all works for ANY count, including 1).
 * @param {Array} tasks already sorted ascending by sendAt
 * @param {{user?: 'expanded'|'collapsed'|null, mobile?: boolean}} [opts]
 */
function collapseState(tasks, { user = null, mobile = false } = {}) {
  const list = tasks || [];
  if (!list.length) {
    return { display: 'expanded', visibleCount: 0, hiddenCount: 0, summary: null, collapsed: false };
  }
  let display = mobile ? 'summary' : (list.length > 1 ? 'one' : 'expanded');
  if (user === 'expanded') display = 'expanded';
  else if (user === 'collapsed') display = list.length > 1 ? 'one' : 'summary';
  if (display === 'one') {
    return { display, visibleCount: 1, hiddenCount: list.length - 1, summary: `${list.length - 1} more scheduled ⌄`, collapsed: true };
  }
  if (display === 'summary') {
    return { display, visibleCount: 0, hiddenCount: list.length, summary: `${list.length} scheduled ⌄`, collapsed: true };
  }
  return { display: 'expanded', visibleCount: list.length, hiddenCount: 0, summary: 'Collapse ⌃', collapsed: false };
}

/** Local-timezone "YYYY-MM-DD HH:mm" for a planned send time. */
function formatLocalTime(ms) {
  if (typeof ms !== 'number' || !Number.isFinite(ms)) return '';
  const d = new Date(ms);
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/** Countdown until sendAt ("1m 30s" / "1h 0m" / "2d 3h"), or "now" once due. */
function formatCountdown(sendAt, now) {
  const ms = sendAt - now;
  if (ms <= 0) return 'now';
  const totalSec = Math.floor(ms / 1000);
  const d = Math.floor(totalSec / 86400);
  const h = Math.floor((totalSec % 86400) / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  // a bare duration: callers frame it ("Sends in …") via sendsIn below
  if (d > 0) return `${d}d ${h}h`;
  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

/**
 * The countdown as a phrase: "Sends in 4m 12s", or "Sending now" once due.
 *
 * English puts the verb in front of the duration, where the original appended
 * it after the duration. Doing that at each call site as "Sends in " + countdown
 * would print "Sends in now" for a due task, so the phrasing lives here.
 */
function sendsIn(sendAt, now) {
  const left = formatCountdown(sendAt, now);
  return left === 'now' ? 'Sending now' : `Sends in ${left}`;
}

/** Default confirmation time = now + 5 minutes. */
function defaultSendAt(now = Date.now(), offsetMs = 5 * 60_000) {
  return now + offsetMs;
}

/**
 * One-line content summary for the sidebar panel list (0.3.0): first line,
 * trimmed; capped with an ellipsis past `max` chars. Empty input → ''.
 */
function summarizeContent(text, max = 50) {
  if (typeof text !== 'string') return '';
  const first = text.split(/\r?\n/, 1)[0].trim();
  if (!first) return '';
  return first.length > max ? first.slice(0, max - 1) + '…' : first;
}

/**
 * Attach session identity to panel rows (0.3.0): `sessionTitle` from the
 * client session list's displayTitle, `sessionExists` false when the session
 * is gone (deleted / not in the list) — those rows gray out but stay
 * cancellable. Never throws on a missing/empty map.
 */
function annotateSessions(tasks, sessionsById) {
  const byId = sessionsById || {};
  return (tasks || []).map((t) => {
    const s = t?.conversationId ? byId[t.conversationId] : null;
    return {
      ...t,
      sessionExists: !!s,
      sessionTitle: s ? (s.displayTitle || s.title || t.conversationId) : '',
    };
  });
}

/**
 * Stateful client controller: polls the host state route, holds the visible
 * task list (extended with the server-confirmed task right after POST so new
 * entries show WITHOUT a refresh), and exposes cancel.
 *
 * FIX 1: setSession() reports session changes so the view can refresh
 * immediately; refresh failures keep the LAST data and surface an error
 * instead of flashing empty.
 *
 * FIX 4: refresh() merges by id — a recently POSTed task (within
 * LOCAL_ADD_GRACE_MS) survives a stale server snapshot that predates it.
 *
 * @param {object} deps
 * @param {() => Promise<object>} deps.fetchState GET the host state route
 * @param {(payload:object)=>Promise<{task:object}>} deps.postSchedule
 * @param {(id:string)=>Promise<boolean>} deps.cancelSchedule
 * @param {() => number} [deps.now]
 */
function createScheduledClientState({ fetchState, postSchedule, cancelSchedule, now = () => Date.now() } = {}) {
  let tasks = [];
  let error = null;
  let timer = null;
  let stopped = false;
  let sessionId = null; // this dock belongs to exactly one conversation
  const recentAdds = new Map(); // id → addedAt (FIX 4 grace window)
  // per-conversation cache: switching sessions shows the cached list
  // INSTANTLY (no ~1s wait for the network), then refresh() revalidates.
  const sessionCache = new Map(); // sid → task[]

  // strict conversation filter: with a session bound, only entries belonging
  // to THIS conversation are ever visible; other-session tasks are dropped
  // from the local list on every refresh.
  const own = (it) => !sessionId || !it?.conversationId || it.conversationId === sessionId;
  const dedupeById = (list) => {
    const seen = new Set();
    return list.filter((t) => (t?.id && !seen.has(t.id) ? (seen.add(t.id), true) : false));
  };

  return {
    /**
     * Bind this client to one conversation. Returns true when the session
     * actually CHANGED (the view refreshes immediately in that case — FIX 1).
     */
    setSession(sid) {
      const next = sid || null;
      const changed = next !== sessionId;
      if (sessionId !== null) sessionCache.set(sessionId, tasks.filter(own));
      sessionId = next;
      if (changed) {
        // instant swap: show the cached list for the target session first
        tasks = sessionId !== null && sessionCache.has(sessionId)
          ? [...sessionCache.get(sessionId)]
          : [];
        error = null;
      }
      return changed;
    },

    /** Session this client is currently bound to (view fetch uses it). */
    currentSession() {
      return sessionId;
    },

    /** Pending tasks sorted ascending by sendAt, own session only. */
    visibleTasks() {
      return sortTasks(tasks).filter(own);
    },
    /** Last refresh error, or null (view shows old data + this line). */
    lastError() {
      return error;
    },
    snapshot() {
      return { tasks: sortTasks(tasks).filter(own), error, fetchedAt: now() };
    },

    async refresh() {
      let s;
      try {
        s = await fetchState();
      } catch (err) {
        // FIX 1 failure mode: keep the previous list, surface the error —
        // never flash an empty dock on a transient failure.
        error = String(err?.message || err);
        return this.snapshot();
      }
      error = null;
      const server = (s?.tasks ?? []).filter(own);
      // FIX 4: keep freshly POSTed tasks whose id the (possibly stale) server
      // snapshot does not know yet; the server list stays authoritative for
      // everything else (cancellations included).
      const t = now();
      const freshLocal = tasks.filter(
        (it) => it?.id && !server.some((x) => x.id === it.id) && own(it) && t - (recentAdds.get(it.id) ?? -Infinity) < LOCAL_ADD_GRACE_MS,
      );
      for (const id of [...recentAdds.keys()]) {
        if (t - recentAdds.get(id) >= LOCAL_ADD_GRACE_MS || server.some((x) => x.id === id)) recentAdds.delete(id);
      }
      tasks = dedupeById([...server, ...freshLocal]);
      if (sessionId !== null) sessionCache.set(sessionId, tasks); // keep the instant-swap cache fresh
      return this.snapshot();
    },

    /**
     * User-facing schedule entry: POST to the host route and locally enqueue
     * the SERVER-RETURNED task so it is visible IMMEDIATELY (no refresh needed,
     * id-deduped). Nothing is added on failure, so the view keeps the form
     * with its content intact (a failure rolls back and keeps the form).
     */
    async scheduleMessage(payload) {
      if (!postSchedule) throw new Error('postSchedule is not configured');
      const result = await postSchedule(payload);
      const task = result?.task ?? result;
      if (task?.id && own(task)) {
        tasks = dedupeById([...tasks, task]);
        recentAdds.set(task.id, now());
      }
      return task;
    },

    /** Cancel a pending task: DELETE on the host + drop locally. */
    /** Cross-instance optimistic removal by id (no fetch). */
    removeTask(id) {
      tasks = tasks.filter((t) => t.id !== id);
      recentAdds.delete(id);
    },

    async cancelTask(id) {
      // optimistic: drop locally FIRST so the row disappears instantly; the
      // DELETE then persists it. onChanged lets the sibling instance (dock ↔
      // sidebar panel) refresh immediately instead of waiting for its poll.
      tasks = tasks.filter((t) => t.id !== id);
      recentAdds.delete(id);
      if (typeof this.onChanged === 'function') this.onChanged(id);
      if (cancelSchedule) await cancelSchedule(id);
    },

    start(intervalMs = 4_000) {
      if (timer) return;
      stopped = false;
      const loop = async () => {
        if (stopped) return;
        await this.refresh().catch(() => {});
        timer = setTimeout(loop, intervalMs);
        timer.unref?.();
      };
      void loop();
    },

    stop() {
      stopped = true;
      clearTimeout(timer);
      timer = null;
    },
  };
}

// Browser view layer for dsh-schedule-later.
// This file is CONCATENATED into lib/client.js by scripts/build-client.mjs
// together with src/client-core.js — it must stay import/export-free plain JS.
// Inside the bundle it references: React (platform module) and the client-core
// helpers (sortTasks/collapseState/formatLocalTime/formatCountdown/…).

/* ==== view ==== */
function createClientPluginBody(React) {
  const h = React.createElement;
  const TOUCH_MIN = 40; // FIX 5: touch target height on mobile

  /* --- motion ---------------------------------------------------------- */
  // One stylesheet for every animation in the plugin, added once. Anything
  // marked .dsl-motion stops moving when the OS asks for reduced motion.
  const STYLE_ID = "dsh-schedule-later-motion";
  const MOTION_CSS = [
    "@keyframes dsl-sweep{to{transform:rotate(360deg)}}",
    "@keyframes dsl-nudge{0%,100%{transform:rotate(0)}30%{transform:rotate(45deg)}65%{transform:rotate(-10deg)}}",
    "@keyframes dsl-flip{0%,35%{transform:rotate(0)}50%,85%{transform:rotate(180deg)}100%{transform:rotate(360deg)}}",
    "@keyframes dsl-twinkle{0%,100%{opacity:.25}50%{opacity:1}}",
    "@keyframes dsl-pop{from{opacity:0;transform:translateY(6px) scale(.98)}to{opacity:1;transform:none}}",
    "@keyframes dsl-glow{0%,100%{opacity:.5;transform:scale(1)}50%{opacity:.85;transform:scale(1.25)}}",
    ".dsl-hand{transform-box:view-box;transform-origin:12px 14px}",
    ".dsl-spin .dsl-hand{animation:dsl-sweep 2.4s linear infinite}",
    ".dsl-slow .dsl-hand{animation:dsl-sweep 10s linear infinite}",
    ".dsl-btn:hover .dsl-watch:not(.dsl-spin) .dsl-hand{animation:dsl-nudge .7s ease-in-out}",
    ".dsl-flip{animation:dsl-flip 2.6s ease-in-out infinite;transform-origin:50% 50%}",
    ".dsl-twinkle{animation:dsl-twinkle 2.4s ease-in-out infinite}",
    ".dsl-pop{animation:dsl-pop .18s ease-out}",
    ".dsl-glow{animation:dsl-glow 3s ease-in-out infinite;transform-box:fill-box;transform-origin:center}",
    ".dsl-chip:hover{border-color:#3b82f6!important}",
    // The in-chat list's scrollbar, in dsh's own style: a thin rounded thumb
    // inset 2px on a clear track, no buttons.
    ".dsl-dock-list::-webkit-scrollbar{width:8px}",
    ".dsl-dock-list::-webkit-scrollbar-button{display:none;width:0;height:0}",
    ".dsl-dock-list::-webkit-scrollbar-track{background:transparent}",
    ".dsl-dock-list::-webkit-scrollbar-thumb{background-color:rgba(128,128,128,.4);border:2px solid transparent;background-clip:padding-box;border-radius:6px}",
    ".dsl-dock-list::-webkit-scrollbar-thumb:hover{background-color:rgba(128,128,128,.6)}",
    "@keyframes dsl-sunturn{0%,100%{transform:rotate(0) scale(1)}50%{transform:rotate(45deg) scale(1.15)}}",
    "@keyframes dsl-moonglow{0%,100%{opacity:.6}50%{opacity:1}}",
    "@keyframes dsl-due{0%,100%{box-shadow:0 0 0 0 rgba(59,130,246,0)}50%{box-shadow:0 0 0 3px rgba(59,130,246,.38)}}",
    ".dsl-sunturn{animation:dsl-sunturn 6s ease-in-out infinite;transform-origin:50% 50%}",
    ".dsl-moonglow{animation:dsl-moonglow 3.2s ease-in-out infinite}",
    ".dsl-due{animation:dsl-due 1.4s ease-in-out infinite}",
    "@media (prefers-reduced-motion:reduce){.dsl-motion,.dsl-motion *{animation:none!important;transition:none!important}}",
  ].join("\n");

  function ensureStyles() {
    try {
      if (typeof document === "undefined" || document.getElementById(STYLE_ID)) return;
      const el = document.createElement("style");
      el.id = STYLE_ID;
      el.textContent = MOTION_CSS;
      document.head.appendChild(el);
    } catch { /* no DOM (tests) — icons still render, just without motion */ }
  }

  /* --- icons ------------------------------------------------------------ */
  /**
   * Stopwatch, drawn as an outline in the text colour so it sits with dsh's own
   * icons instead of standing out as a full-colour emoji. `currentColor` makes
   * it follow the theme, the hover state and the button's blue "open" state.
   * @param motion - "" (still; nudges on hover inside .dsl-btn), "spin"
   *   (sweeping: scheduling now) or "slow" (ticking: something is pending).
   */
  function StopwatchIcon(size, motion) {
    return h("svg", {
      width: size, height: size, viewBox: "0 0 24 24", fill: "none",
      stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round", strokeLinejoin: "round",
      "aria-hidden": "true", style: { flex: "none", display: "block" },
      className: "dsl-motion dsl-watch" + (motion ? " dsl-" + motion : ""),
    }, [
      h("line", { key: "cap", x1: 10, y1: 2, x2: 14, y2: 2 }),
      h("line", { key: "stem", x1: 12, y1: 2, x2: 12, y2: 6 }),
      h("line", { key: "hand", className: "dsl-hand", x1: 12, y1: 14, x2: 15, y2: 11 }),
      h("circle", { key: "face", cx: 12, cy: 14, r: 8 }),
    ]);
  }

  /** Hourglass that turns over: "waiting to send". */
  function HourglassIcon(size) {
    return h("svg", {
      width: size, height: size, viewBox: "0 0 24 24", fill: "none",
      stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round", strokeLinejoin: "round",
      "aria-hidden": "true", className: "dsl-motion dsl-flip",
      style: { flex: "none", display: "inline-block", verticalAlign: "-2px" },
    }, [
      h("line", { key: "t", x1: 6, y1: 2, x2: 18, y2: 2 }),
      h("line", { key: "b", x1: 6, y1: 22, x2: 18, y2: 22 }),
      h("path", { key: "l", d: "M7 2c0 4 5 6 5 10s-5 6-5 10" }),
      h("path", { key: "r", d: "M17 2c0 4-5 6-5 10s5 6 5 10" }),
      h("path", { key: "sand", d: "M9.2 20c.9-1.8 1.9-2.8 2.8-2.8s1.9 1 2.8 2.8z", fill: "currentColor", stroke: "none", opacity: 0.55 }),
    ]);
  }

  function SunGlyph(size, color) {
    const rays = [];
    for (let i = 0; i < 8; i += 1) {
      const a = (i * Math.PI) / 4;
      rays.push(h("line", {
        key: "r" + i, x1: 12 + Math.cos(a) * 7, y1: 12 + Math.sin(a) * 7,
        x2: 12 + Math.cos(a) * 9.5, y2: 12 + Math.sin(a) * 9.5,
      }));
    }
    return h("svg", {
      width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: color || "currentColor",
      strokeWidth: 2, strokeLinecap: "round", "aria-hidden": "true", style: { flex: "none", display: "inline-block", verticalAlign: "-2px" },
    }, [h("circle", { key: "c", cx: 12, cy: 12, r: 4, fill: color || "currentColor" }), ...rays]);
  }

  function MoonGlyph(size, color) {
    return h("svg", {
      width: size, height: size, viewBox: "0 0 24 24", "aria-hidden": "true",
      style: { flex: "none", display: "inline-block", verticalAlign: "-2px" },
    }, h("path", { d: "M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5z", fill: color || "currentColor" }));
  }

  /* --- time helpers ------------------------------------------------------ */
  function pad2(n) { return String(n).padStart(2, "0"); }

  function toDatetimeLocalValue(ms) {
    const d = new Date(ms);
    return d.getFullYear() + "-" + pad2(d.getMonth() + 1) + "-" + pad2(d.getDate())
      + "T" + pad2(d.getHours()) + ":" + pad2(d.getMinutes());
  }

  /** The datetime-local value as epoch ms (local time), or NaN. */
  function parseLocal(value) {
    return value ? new Date(value).getTime() : NaN;
  }

  /** 12-hour clock parts. Always AM/PM, whatever the locale: that is the point. */
  function clock12(d) {
    const hour = d.getHours();
    return { h12: hour % 12 || 12, mm: pad2(d.getMinutes()), ampm: hour < 12 ? "AM" : "PM" };
  }

  const PHASES = {
    night: { label: "Night", top: "#0b1026", bottom: "#29346f" },
    dawn: { label: "Early morning", top: "#6f7fd1", bottom: "#f7b58a" },
    morning: { label: "Morning", top: "#4f9ee8", bottom: "#c3e4ff" },
    afternoon: { label: "Afternoon", top: "#2f86db", bottom: "#a3d5ff" },
    evening: { label: "Evening", top: "#5b3f8c", bottom: "#f08a5d" },
  };

  function phaseOf(hour) {
    if (hour < 5) return "night";
    if (hour < 7) return "dawn";
    if (hour < 12) return "morning";
    if (hour < 17) return "afternoon";
    if (hour < 20) return "evening";
    return "night";
  }

  /** Sun is up 06:00–18:00 in this picture — simple, and never ambiguous. */
  function isDaytime(hour) { return hour >= 6 && hour < 18; }

  function hourOf(d) { return d.getHours() + d.getMinutes() / 60; }

  /** "Today · Wed 23 Sep", "Tomorrow · Thu 24 Sep", or just the date. */
  function dayLine(ms, now) {
    const d = new Date(ms);
    const midnight = (x) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
    const diff = Math.round((midnight(d) - midnight(new Date(now))) / 86_400_000);
    const date = d.toLocaleDateString(undefined, { weekday: "short", day: "numeric", month: "short" });
    if (diff === 0) return "Today · " + date;
    if (diff === 1) return "Tomorrow · " + date;
    if (diff === -1) return "Yesterday · " + date;
    return date;
  }

  /**
   * The colour of a scheduled message's time of day, as "r,g,b" so it can be
   * used at any strength. Chosen to read on both themes: indigo night, peach
   * dawn, blue day, orange dusk — the popover's sky, one shade each.
   */
  const PHASE_TINT = {
    night: "99,102,241",
    dawn: "244,162,97",
    morning: "79,158,232",
    afternoon: "59,130,246",
    evening: "231,111,81",
  };

  /**
   * How a scheduled-message row looks for its send time: a faint sky wash
   * from the left, an accent stripe, and a pulse in its last minute.
   */
  function skyRow(sendAt, now) {
    const hour = hourOf(new Date(sendAt));
    const rgb = PHASE_TINT[phaseOf(hour)];
    const left = sendAt - now;
    const soon = left > 0 && left <= 60_000;
    return {
      className: "dsl-motion" + (soon ? " dsl-due" : ""),
      style: {
        background: "linear-gradient(90deg, rgba(" + rgb + ",.26) 0%, rgba(" + rgb + ",.10) 45%, rgba(" + rgb + ",.04) 100%)",
        border: "1px solid rgba(" + rgb + ",.32)",
        borderLeft: "3px solid rgb(" + rgb + ")",
        transition: "background .6s, border-color .6s",
      },
    };
  }

  /** "Today", "Tomorrow", a weekday within the week, else a short date. */
  function shortDay(ms, now) {
    const d = new Date(ms);
    const midnight = (x) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
    const diff = Math.round((midnight(d) - midnight(new Date(now))) / 86_400_000);
    if (diff === 0) return "Today";
    if (diff === 1) return "Tomorrow";
    if (diff === -1) return "Yesterday";
    if (diff > 1 && diff < 7) return d.toLocaleDateString(undefined, { weekday: "long" });
    return d.toLocaleDateString(undefined, { day: "numeric", month: "short" });
  }

  /**
   * "Today · ☀ 3:42 PM": the day, then the time in a pill with its sun or
   * moon — the same pill as the scheduler. The exact timestamp is the tooltip.
   */
  function whenPill(sendAt, now, isDark) {
    const d = new Date(sendAt);
    const parts = clock12(d);
    const day = isDaytime(hourOf(d));
    return h("span", {
      key: "at", title: formatLocalTime(sendAt),
      style: { display: "inline-flex", alignItems: "center", gap: 6, flexShrink: 0 },
    }, [
      h("span", { key: "d" }, shortDay(sendAt, now)),
      h("span", {
        key: "p",
        style: {
          display: "inline-flex", alignItems: "center", gap: 4, padding: "0 7px", borderRadius: 999,
          fontSize: 11, fontWeight: 700, lineHeight: "18px", fontVariantNumeric: "tabular-nums",
          background: day ? "rgba(251,191,36,.18)" : "rgba(99,102,241,.22)",
          color: day ? (isDark ? "#fcd34d" : "#b45309") : (isDark ? "#c7d2fe" : "#4338ca"),
        },
      }, [
        h("span", { key: "g", className: "dsl-motion " + (day ? "dsl-sunturn" : "dsl-moonglow"), style: { display: "inline-flex" } },
          day ? SunGlyph(11) : MoonGlyph(11)),
        h("span", { key: "t" }, parts.h12 + ":" + parts.mm + " " + parts.ampm),
      ]),
    ]);
  }

  /** Rounded UP to the next whole minute: "+5 min" never lands at 4m 30s. */
  function ceilMinute(ms) { return Math.ceil(ms / 60_000) * 60_000; }

  function presetsFor(now) {
    const out = [
      { key: "5m", label: "+5 min", at: ceilMinute(now + 5 * 60_000) },
      { key: "15m", label: "+15 min", at: ceilMinute(now + 15 * 60_000) },
      { key: "1h", label: "+1 hour", at: ceilMinute(now + 60 * 60_000) },
    ];
    const tonight = new Date(now);
    tonight.setHours(21, 0, 0, 0);
    if (tonight.getTime() - now > 10 * 60_000) out.push({ key: "tonight", label: "Tonight 9 PM", at: tonight.getTime(), night: true });
    const tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(9, 0, 0, 0);
    out.push({ key: "tomorrow", label: "Tomorrow 9 AM", at: tomorrow.getTime(), day: true });
    return out;
  }

  /**
   * An angle that turns the SHORT way from the previous one: 350° → 10° goes
   * forward 20°, not backwards 340°, so the hands never spin wildly.
   */
  function useTurn(deg) {
    const last = React.useRef(deg);
    const next = deg + 360 * Math.round((last.current - deg) / 360);
    last.current = next;
    return next;
  }

  /* --- sky: day or night, at a glance ------------------------------------ */
  function SkyBand(props) {
    const d = new Date(Number.isFinite(props.ms) ? props.ms : Date.now());
    const hour = hourOf(d);
    const phase = phaseOf(hour);
    const day = isDaytime(hour);
    const clamp = (p) => Math.min(1, Math.max(0, p));
    // Along an arc: rises at the left, highest at noon/midnight, sets right.
    // The peak stays clear of the title row across the top of the band.
    const place = (p) => ({
      left: "calc(" + (6 + clamp(p) * 88).toFixed(2) + "% - 9px)",
      bottom: Math.round(10 + Math.sin(clamp(p) * Math.PI) * 24) + "px",
    });
    const orb = (extra) => ({
      position: "absolute", width: 18, height: 18,
      transition: "left .8s cubic-bezier(.2,.8,.2,1), bottom .8s cubic-bezier(.2,.8,.2,1), opacity .6s",
      ...extra,
    });
    const starsOpacity = phase === "night" ? 1 : phase === "dawn" || phase === "evening" ? 0.3 : 0;
    const stars = [[12, 40], [22, 58], [34, 36], [48, 50], [61, 34], [73, 56], [86, 42], [93, 62]];
    const P = PHASES[phase];

    return h("div", {
      className: "dsl-motion", "aria-hidden": "true",
      style: {
        // Spans the whole popover; the popover's own rounded, clipped
        // shell gives it its corners.
        position: "relative", height: 84, overflow: "hidden", flex: "none",
      },
    }, [
      ...Object.keys(PHASES).map((id) => h("div", {
        key: "sky-" + id,
        style: {
          position: "absolute", inset: 0,
          background: "linear-gradient(180deg," + PHASES[id].top + " 0%," + PHASES[id].bottom + " 100%)",
          opacity: id === phase ? 1 : 0, transition: "opacity .8s ease",
        },
      })),
      h("div", { key: "stars", style: { position: "absolute", inset: 0, opacity: starsOpacity, transition: "opacity .8s" } },
        stars.map(([x, y], i) => h("span", {
          key: "s" + i, className: "dsl-twinkle",
          style: {
            position: "absolute", left: x + "%", top: y + "%", width: i % 3 === 0 ? 3 : 2, height: i % 3 === 0 ? 3 : 2,
            borderRadius: 999, background: "#fff", animationDelay: (i * 0.37).toFixed(2) + "s",
          },
        }))),
      h("div", { key: "sun", style: orb({ ...place((hour - 6) / 12), opacity: day ? 1 : 0 }) }, [
        h("div", { key: "halo", className: "dsl-glow", style: { position: "absolute", inset: -7, borderRadius: 999, background: "radial-gradient(circle, rgba(253,224,71,.8), rgba(253,224,71,0) 70%)" } }),
        h("div", { key: "disc", style: { position: "absolute", inset: 0, borderRadius: 999, background: "radial-gradient(circle at 35% 35%, #fff7c2, #fbbf24 60%, #f59e0b)" } }),
      ]),
      h("div", { key: "moon", style: orb({ ...place(((hour - 18 + 24) % 24) / 12), opacity: day ? 0 : 1 }) },
        h("div", { style: { position: "absolute", inset: 0, borderRadius: 999, background: "#f1f5ff", boxShadow: "inset -5px -3px 0 0 #c7d2fe, 0 0 10px rgba(226,232,255,.6)" } })),
      h("svg", {
        key: "hills", viewBox: "0 0 100 20", preserveAspectRatio: "none",
        style: { position: "absolute", left: 0, right: 0, bottom: 0, width: "100%", height: 16 },
      }, h("path", { d: "M0 14 Q18 6 36 12 T70 10 T100 12 V20 H0z", fill: "rgba(0,0,0,.28)" })),
      h("div", {
        key: "head",
        style: {
          position: "absolute", top: 8, left: 12, right: 10, display: "flex", alignItems: "center", gap: 8,
          color: "#fff", textShadow: "0 1px 2px rgba(0,0,0,.45)",
        },
      }, [
        h("span", { key: "t", style: { fontWeight: 700, fontSize: 13 } }, props.title),
        h("span", {
          key: "p",
          style: {
            marginLeft: "auto", display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, fontWeight: 600,
            padding: "2px 8px", borderRadius: 999, background: "rgba(0,0,0,.28)", textShadow: "none",
          },
        }, [day ? SunGlyph(12, "#fde047") : MoonGlyph(12, "#e0e7ff"), h("span", { key: "l" }, P.label)]),
      ]),
    ]);
  }

  /* --- analog clock beside the time -------------------------------------- */
  function TimeDial(props) {
    const d = new Date(Number.isFinite(props.ms) ? props.ms : Date.now());
    const hr = d.getHours();
    const min = d.getMinutes();
    const night = !isDaytime(hourOf(d));
    const hourDeg = useTurn(((hr % 12) + min / 60) * 30);
    const minDeg = useTurn(min * 6);
    const face = night ? "#101a3a" : props.isDark ? "#f5f7fb" : "#ffffff";
    const ink = night ? "#e0e7ff" : "#1f2937";
    const ring = night ? "#3b4a8a" : props.isDark ? "rgba(255,255,255,.35)" : "rgba(0,0,0,.16)";
    const turn = (deg) => ({
      transform: "rotate(" + deg + "deg)", transformBox: "view-box", transformOrigin: "50px 50px",
      transition: "transform .8s cubic-bezier(.2,.8,.2,1)",
    });
    const ticks = [];
    for (let i = 0; i < 12; i += 1) {
      const a = (i * Math.PI) / 6;
      const inner = i % 3 === 0 ? 33 : 37;
      ticks.push(h("line", {
        key: "k" + i, x1: 50 + Math.sin(a) * inner, y1: 50 - Math.cos(a) * inner,
        x2: 50 + Math.sin(a) * 41, y2: 50 - Math.cos(a) * 41,
        stroke: ink, strokeWidth: i % 3 === 0 ? 3 : 1.6, strokeLinecap: "round", opacity: i % 3 === 0 ? 0.9 : 0.45,
        style: { transition: "stroke .6s" },
      }));
    }
    return h("svg", {
      className: "dsl-motion", width: props.size || 76, height: props.size || 76, viewBox: "0 0 100 100", "aria-hidden": "true",
      style: { flex: "none", display: "block" },
    }, [
      h("circle", { key: "face", cx: 50, cy: 50, r: 46, style: { fill: face, stroke: ring, strokeWidth: 2, transition: "fill .6s, stroke .6s" } }),
      ...(night
        ? [[30, 30], [70, 27], [67, 72]].map(([x, y], i) => h("circle", {
            key: "st" + i, cx: x, cy: y, r: 1.4, fill: "#fff", className: "dsl-twinkle",
            style: { animationDelay: (i * 0.6).toFixed(1) + "s" },
          }))
        : []),
      ...ticks,
      h("g", { key: "hh", style: turn(hourDeg) },
        h("line", { x1: 50, y1: 52, x2: 50, y2: 26, stroke: ink, strokeWidth: 5, strokeLinecap: "round", style: { transition: "stroke .6s" } })),
      h("g", { key: "mh", style: turn(minDeg) },
        h("line", { x1: 50, y1: 54, x2: 50, y2: 13, stroke: "#3b82f6", strokeWidth: 3, strokeLinecap: "round" })),
      h("circle", { key: "pin", cx: 50, cy: 50, r: 3.5, fill: "#3b82f6", stroke: face, strokeWidth: 1.5 }),
      // Over the hands, with a halo in the face colour, so a hand passing
      // through never hides whether this is morning or night.
      h("text", {
        key: "ampm", x: 50, y: 75, textAnchor: "middle", fontSize: 12, fontWeight: 800,
        stroke: face, strokeWidth: 4, strokeLinejoin: "round",
        style: { fill: ink, paintOrder: "stroke", letterSpacing: ".5px", transition: "fill .6s, stroke .6s" },
      }, hr < 12 ? "AM" : "PM"),
    ]);
  }

  /* --- date & time picker: the popover's right-hand extension ------------ */
  const MAIN_W = 320;
  const EXT_W = 284;
  const WEEKDAYS = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];

  /** The sky across one day, left (midnight) to right (midnight). */
  const DAY_GRADIENT = "linear-gradient(90deg,#0b1026 0%,#1f2a5c 17%,#f7b58a 25%,#7cc0f5 32%,#4aa3f0 50%,#7cc0f5 68%,#f08a5d 76%,#5b3f8c 82%,#141b3d 90%,#0b1026 100%)";

  /** A datetime-local string with some fields replaced; the day is clamped to the month. */
  function withParts(value, patch, now) {
    const ms = parseLocal(value);
    const base = new Date(Number.isFinite(ms) ? ms : ceilMinute(now + 5 * 60_000));
    const year = patch.year ?? base.getFullYear();
    const month = patch.month ?? base.getMonth();
    const lastDay = new Date(year, month + 1, 0).getDate();
    const day = Math.min(patch.day ?? base.getDate(), lastDay);
    const hour = patch.hour ?? base.getHours();
    const minute = patch.minute ?? base.getMinutes();
    return toDatetimeLocalValue(new Date(year, month, day, hour, minute).getTime());
  }

  /** Move by real time, so 11:30 PM + 1 hour rolls onto the next day. */
  function shifted(value, minutes, now) {
    const ms = parseLocal(value);
    const base = Number.isFinite(ms) ? ms : ceilMinute(now + 5 * 60_000);
    return toDatetimeLocalValue(base + minutes * 60_000);
  }

  /** Minutes snap to :05 steps: 23 → up 25, down 20. */
  function snappedMinute(value, direction, now) {
    const ms = parseLocal(value);
    const d = new Date(Number.isFinite(ms) ? ms : ceilMinute(now + 5 * 60_000));
    const m = d.getMinutes();
    const target = direction > 0 ? (Math.floor(m / 5) + 1) * 5 : (Math.ceil(m / 5) - 1) * 5;
    return shifted(value, target - m, now);
  }

  /**
   * Turn the mouse wheel over `ref` into steps: one per notch, and a
   * trackpad's many small deltas add up to the same. Wheel up is later, like
   * ▲ and like a number field. Registered natively and non-passive — React's
   * onWheel is passive, so it could not stop the chat behind from scrolling.
   * @param onStep - called with a signed whole number of steps.
   * @param ignore - optional: a wheel over a target this accepts scrolls normally.
   */
  function useWheel(ref, onStep, ignore) {
    const latest = React.useRef({ onStep, ignore });
    latest.current = { onStep, ignore };
    React.useEffect(() => {
      const el = ref.current;
      if (!el || typeof el.addEventListener !== "function") return undefined;
      let pending = 0;
      const onWheel = (e) => {
        if (latest.current.ignore && latest.current.ignore(e.target)) return;
        e.preventDefault();
        pending += e.deltaMode === 1 ? e.deltaY * 33 : e.deltaMode === 2 ? e.deltaY * 400 : e.deltaY;
        const steps = Math.trunc(pending / 100);
        if (steps === 0) return;
        pending -= steps * 100;
        latest.current.onStep(-steps);
      };
      el.addEventListener("wheel", onWheel, { passive: false });
      return () => el.removeEventListener("wheel", onWheel);
    }, []);
  }

  /**
   * One column of the time: ▲ / value / ▼. Scroll over it to step; click the
   * value for a scrollable list to pick from.
   */
  function TimeColumn(p) {
    const boxRef = React.useRef(null);
    const listRef = React.useRef(null);
    useWheel(boxRef, p.onStep, (target) => !!listRef.current && typeof listRef.current.contains === "function" && listRef.current.contains(target));
    // Opening the list puts the current value in its middle.
    React.useEffect(() => {
      if (!p.open) return;
      const list = listRef.current;
      const current = list && typeof list.querySelector === "function" ? list.querySelector('[aria-selected="true"]') : null;
      if (list && current) list.scrollTop = current.offsetTop - (list.clientHeight - current.offsetHeight) / 2;
    }, [p.open]);
    const arrow = (label, n, glyph) => h("button", {
      key: label, type: "button", "aria-label": label, onClick: () => p.onStep(n),
      style: {
        cursor: "pointer", border: "none", background: "transparent", color: p.muted, width: 40, height: 18,
        padding: 0, fontSize: 10, lineHeight: "18px", borderRadius: 6, ...(p.mobile ? { minHeight: TOUCH_MIN, width: 48 } : {}),
      },
    }, glyph);
    return h("div", {
      ref: boxRef, "data-time-column": p.id, title: "Scroll to change · click to pick",
      style: { position: "relative", display: "flex", flexDirection: "column", alignItems: "center" },
    }, [
      arrow(p.laterLabel, 1, "▲"),
      h("button", {
        key: "v", type: "button", "aria-label": p.label, "aria-haspopup": "listbox", "aria-expanded": !!p.open,
        onClick: p.onToggle,
        style: {
          cursor: "pointer", border: "none", color: "inherit", fontSize: 24, fontWeight: 700, fontVariantNumeric: "tabular-nums",
          lineHeight: "34px", minWidth: 50, padding: "0 4px", borderRadius: 8,
          background: p.open ? "rgba(59,130,246,.18)" : p.isDark ? "rgba(255,255,255,.07)" : "rgba(0,0,0,.05)",
          boxShadow: p.open ? "inset 0 0 0 1.5px #3b82f6" : "none",
          ...(p.mobile ? { minHeight: TOUCH_MIN } : {}),
        },
      }, p.text),
      arrow(p.earlierLabel, -1, "▼"),
      p.open
        ? h("div", {
            key: "list", ref: listRef, role: "listbox", "aria-label": p.label,
            style: {
              position: "absolute", bottom: "calc(100% + 4px)", left: "50%", transform: "translateX(-50%)", zIndex: 5,
              width: 64, maxHeight: 184, overflowY: "auto", overscrollBehavior: "contain", padding: 4, boxSizing: "border-box",
              display: "flex", flexDirection: "column", gap: 2, borderRadius: 10,
              border: "1px solid " + p.hairline, background: p.isDark ? "#26262a" : "#fff", boxShadow: "0 8px 20px rgba(0,0,0,.3)",
            },
          }, p.options.map((o) => h("button", {
            key: o.key, type: "button", role: "option", "aria-selected": o.selected, onClick: () => p.onPick(o.value),
            style: {
              cursor: "pointer", border: "none", borderRadius: 6, padding: "4px 0", fontSize: 13, flex: "none",
              fontVariantNumeric: "tabular-nums", fontWeight: o.selected ? 700 : 500,
              background: o.selected ? "#3b82f6" : "transparent", color: o.selected ? "#fff" : "inherit",
              ...(p.mobile ? { minHeight: TOUCH_MIN } : {}),
            },
          }, o.label)))
        : null,
    ]);
  }

  function DateTimePanel(props) {
    const { value, onChange, now, isDark, mobile, muted, hairline } = props;
    const ms = parseLocal(value);
    const sel = new Date(Number.isFinite(ms) ? ms : ceilMinute(now + 5 * 60_000));
    const today = new Date(now);
    const [view, setView] = React.useState(() => ({ y: sel.getFullYear(), m: sel.getMonth() }));
    const [list, setList] = React.useState(null); // which time column has its list open
    const trackRef = React.useRef(null);
    // A quick pick or a stepper that lands in another month brings the calendar with it.
    React.useEffect(() => { setView({ y: sel.getFullYear(), m: sel.getMonth() }); }, [sel.getFullYear(), sel.getMonth()]);

    const sameDay = (a, b) => a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
    const startOfToday = new Date(today.getFullYear(), today.getMonth(), today.getDate()).getTime();
    const atFirstMonth = view.y < today.getFullYear() || (view.y === today.getFullYear() && view.m <= today.getMonth());
    const touch = mobile ? { minHeight: TOUCH_MIN, minWidth: TOUCH_MIN, boxSizing: "border-box" } : {};

    const navBtn = (label, delta, disabled) => h("button", {
      key: label, type: "button", "aria-label": label, disabled,
      onClick: () => setView((v) => {
        const d = new Date(v.y, v.m + delta, 1);
        return { y: d.getFullYear(), m: d.getMonth() };
      }),
      style: {
        cursor: disabled ? "default" : "pointer", opacity: disabled ? 0.3 : 1, border: "none", background: "transparent",
        color: "inherit", width: 26, height: 26, borderRadius: 999, fontSize: 15, lineHeight: "26px", padding: 0, ...touch,
      },
    }, delta < 0 ? "‹" : "›");

    const first = new Date(view.y, view.m, 1);
    const lead = (first.getDay() + 6) % 7; // weeks start on Monday
    const cells = [];
    for (let i = 0; i < 42; i += 1) {
      const d = new Date(view.y, view.m, 1 - lead + i);
      const inMonth = d.getMonth() === view.m;
      const past = d.getTime() < startOfToday;
      const chosen = sameDay(d, sel);
      const isToday = sameDay(d, today);
      cells.push(h("button", {
        key: "d" + i, type: "button", disabled: past,
        "aria-label": d.toDateString(), "aria-pressed": chosen,
        onClick: () => {
          let next = withParts(value, { year: d.getFullYear(), month: d.getMonth(), day: d.getDate() }, now);
          // Today with a time that has already gone: move to the next sensible minute.
          if (parseLocal(next) <= now) next = toDatetimeLocalValue(ceilMinute(now + 5 * 60_000));
          onChange(next);
        },
        style: {
          cursor: past ? "default" : "pointer", border: "none", padding: 0, fontSize: 12,
          height: mobile ? TOUCH_MIN : 28, borderRadius: 999, fontVariantNumeric: "tabular-nums",
          fontWeight: chosen ? 700 : 500,
          background: chosen ? "#3b82f6" : "transparent",
          color: chosen ? "#fff" : "inherit",
          opacity: past ? 0.25 : inMonth ? 1 : 0.4,
          boxShadow: isToday && !chosen ? "inset 0 0 0 1.5px #3b82f6" : "none",
          transition: "background .15s",
        },
      }, String(d.getDate())));
    }

    const hour = sel.getHours();
    const parts = clock12(sel);
    const day = isDaytime(hourOf(sel));
    const minuteSteps = (n) => {
      let next = value;
      for (let i = 0; i < Math.abs(n); i += 1) next = snappedMinute(next, Math.sign(n), now);
      return next;
    };
    const hourOptions = [12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].map((h12) => ({
      key: "h" + h12, label: String(h12).padStart(2, "0"), value: h12, selected: parts.h12 === h12,
    }));
    const minuteValues = [];
    for (let m = 0; m < 60; m += 5) minuteValues.push(m);
    // An exact minute like :23 stays pickable instead of vanishing from the list.
    if (!minuteValues.includes(sel.getMinutes())) minuteValues.push(sel.getMinutes());
    const minuteOptions = minuteValues.sort((a, b) => a - b).map((m) => ({
      key: "m" + m, label: String(m).padStart(2, "0"), value: m, selected: sel.getMinutes() === m,
    }));
    const column = (id, text, onStep, options, onPick, label, laterLabel, earlierLabel) => h(TimeColumn, {
      key: id, id, text, label, laterLabel, earlierLabel, options, isDark, mobile, muted, hairline,
      open: list === id,
      onToggle: () => setList(list === id ? null : id),
      onStep: (n) => { setList(null); onChange(onStep(n)); },
      onPick: (v) => { setList(null); onChange(onPick(v)); },
    });
    const half = (label, isPm) => {
      const active = isPm ? hour >= 12 : hour < 12;
      return h("button", {
        key: label, type: "button", "aria-pressed": active,
        onClick: () => {
          if (isPm && hour < 12) onChange(withParts(value, { hour: hour + 12 }, now));
          if (!isPm && hour >= 12) onChange(withParts(value, { hour: hour - 12 }, now));
        },
        style: {
          cursor: "pointer", border: "none", padding: "4px 10px", fontSize: 11, fontWeight: 700, letterSpacing: ".5px",
          background: active ? "#3b82f6" : "transparent", color: active ? "#fff" : "inherit",
          ...(mobile ? { minHeight: TOUCH_MIN } : {}),
        },
      }, label);
    };

    const minuteOfDay = hour * 60 + sel.getMinutes();
    const pct = (minuteOfDay / 1440) * 100;
    const setFromPointer = (e) => {
      const rect = e.currentTarget.getBoundingClientRect();
      const x = Math.min(Math.max(e.clientX - rect.left, 0), rect.width);
      const total = Math.min(1435, Math.round(((x / rect.width) * 1440) / 5) * 5);
      onChange(withParts(value, { hour: Math.floor(total / 60), minute: total % 60 }, now));
    };
    // Scrolling over the sky moves the time by five minutes a notch, same day.
    useWheel(trackRef, (n) => {
      const total = Math.min(1435, Math.max(0, Math.round(minuteOfDay / 5) * 5 + n * 5));
      onChange(withParts(value, { hour: Math.floor(total / 60), minute: total % 60 }, now));
    });
    const slider = h("div", { key: "slider", style: { marginTop: 12 } }, [
      h("div", {
        key: "track", ref: trackRef, role: "slider", tabIndex: 0, title: "Drag, click or scroll",
        "aria-label": "Time of day", "aria-valuemin": 0, "aria-valuemax": 1435, "aria-valuenow": minuteOfDay,
        "aria-valuetext": parts.h12 + ":" + parts.mm + " " + parts.ampm,
        onPointerDown: (e) => { e.currentTarget.setPointerCapture?.(e.pointerId); setFromPointer(e); },
        onPointerMove: (e) => { if (e.buttons & 1) setFromPointer(e); },
        onKeyDown: (e) => {
          const step = { ArrowRight: 5, ArrowUp: 5, ArrowLeft: -5, ArrowDown: -5, PageUp: 60, PageDown: -60 }[e.key];
          if (step === undefined) return;
          e.preventDefault?.();
          const total = Math.min(1435, Math.max(0, minuteOfDay + step));
          onChange(withParts(value, { hour: Math.floor(total / 60), minute: total % 60 }, now));
        },
        style: {
          position: "relative", height: mobile ? TOUCH_MIN : 24, borderRadius: 999, background: DAY_GRADIENT,
          cursor: "pointer", touchAction: "none", outline: "none",
          boxShadow: "inset 0 0 0 1px rgba(0,0,0,.15)",
        },
      }, [
        h("span", {
          key: "thumb", className: "dsl-motion",
          style: {
            position: "absolute", top: "50%", left: "calc((100% - 22px) * " + (pct / 100).toFixed(4) + ")", width: 22, height: 22,
            marginTop: -11, borderRadius: 999, display: "flex", alignItems: "center", justifyContent: "center",
            background: day ? "#fff7d6" : "#1e2550", border: "2px solid #fff",
            boxShadow: "0 1px 4px rgba(0,0,0,.4)", transition: "left .12s ease-out, background .3s",
          },
        }, day ? SunGlyph(12, "#f59e0b") : MoonGlyph(11, "#e0e7ff")),
      ]),
      h("div", {
        key: "marks",
        style: { display: "flex", justifyContent: "space-between", fontSize: 10, color: muted, marginTop: 4, fontVariantNumeric: "tabular-nums" },
      }, [
        h("span", { key: "a" }, [MoonGlyph(9), " 12 AM"]),
        h("span", { key: "b" }, "6 AM"),
        h("span", { key: "c" }, [SunGlyph(9), " 12 PM"]),
        h("span", { key: "d" }, "6 PM"),
        h("span", { key: "e" }, [MoonGlyph(9), " 12 AM"]),
      ]),
    ]);

    return h("div", {
      "data-plugin": "dsh-schedule-later-picker", style: { display: "flex", flexDirection: "column" },
      // A click anywhere outside the time columns closes an open list.
      onPointerDown: (e) => {
        if (list !== null && !(e.target && typeof e.target.closest === "function" && e.target.closest("[data-time-column]"))) setList(null);
      },
    }, [
      h("div", { key: "head", style: { display: "flex", alignItems: "center", gap: 4, marginBottom: 6 } }, [
        navBtn("Previous month", -1, atFirstMonth),
        h("span", { key: "t", style: { flex: 1, textAlign: "center", fontWeight: 700, fontSize: 13 } },
          first.toLocaleDateString(undefined, { month: "long", year: "numeric" })),
        navBtn("Next month", 1, false),
      ]),
      h("div", { key: "wk", style: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", fontSize: 10, color: muted, textAlign: "center", marginBottom: 2 } },
        WEEKDAYS.map((w) => h("span", { key: w }, w))),
      h("div", { key: "grid", style: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", rowGap: 2 } }, cells),
      h("div", { key: "rule", style: { height: 1, background: hairline, margin: "10px 0" } }),
      h("div", { key: "time", style: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8 } }, [
        column("hh", String(parts.h12).padStart(2, "0"),
          (n) => shifted(value, 60 * n, now),
          hourOptions,
          (h12) => withParts(value, { hour: (h12 % 12) + (hour >= 12 ? 12 : 0) }, now),
          "Hour", "One hour later", "One hour earlier"),
        h("span", { key: "colon", style: { fontSize: 22, fontWeight: 700, opacity: 0.5 } }, ":"),
        column("mm", parts.mm,
          (n) => minuteSteps(n),
          minuteOptions,
          (m) => withParts(value, { minute: m }, now),
          "Minute", "Five minutes later", "Five minutes earlier"),
        h("div", {
          key: "ampm",
          style: { display: "flex", flexDirection: "column", marginLeft: 6, borderRadius: 8, overflow: "hidden", border: "1px solid " + hairline },
        }, [half("AM", false), half("PM", true)]),
      ]),
      slider,
    ]);
  }

  function isMobile() {
    return isMobileViewport(typeof window !== "undefined" ? window.matchMedia : null);
  }

  /* --- ⏱️ composer button (conversation.input.right) -------------------- */
  function ScheduleButton(props) {
    const core = props.core;
    const [open, setOpen] = React.useState(false);
    const [timeValue, setTimeValue] = React.useState("");
    const [busy, setBusy] = React.useState(false);
    const [error, setError] = React.useState(null);
    const [now, setNow] = React.useState(() => Date.now());
    const mobile = isMobile();
    // "side": the picker is a panel on the right. "stack": it folds under
    // the popover, behind a toggle — on phones, and wherever a side panel
    // would run off the screen.
    const [layout, setLayout] = React.useState(mobile ? "stack" : "side");
    const [pickerOpen, setPickerOpen] = React.useState(false);
    const wrapRef = React.useRef(null);
    // standard session props: useInput(s => s.draft) reads the composer draft
    const draft = typeof props.useInput === "function"
      ? (props.useInput((s) => (s == null ? "" : s.draft)) ?? "")
      : "";
    // The popover's message box and the composer are the SAME draft: typing
    // in either shows in the other. `msg` mirrors it locally so typing here
    // never waits on the composer's store.
    const canSync = !!(props.inputActions && typeof props.inputActions.setDraft === "function");
    const [msg, setMsg] = React.useState("");
    // What this box itself pushed recently. When the composer echoes one of
    // these back — possibly late, after newer keystrokes — it is ignored, so
    // a slow echo can never overwrite what was typed since.
    const echoes = React.useRef([]);
    React.useEffect(() => {
      const text = String(draft ?? "");
      if (echoes.current.includes(text)) return;
      setMsg(text);
    }, [draft]);
    const editMsg = (text) => {
      setMsg(text);
      if (!canSync) return;
      echoes.current = [...echoes.current.slice(-19), text];
      props.inputActions.setDraft(text);
    };
    ensureStyles();

    // A live "Sends in …" while the popover is open; nothing ticks when shut.
    React.useEffect(() => {
      if (!open) return undefined;
      setNow(Date.now());
      const t = setInterval(() => setNow(Date.now()), 1000);
      t.unref?.(); // never hold the host loop for a UI countdown
      return () => clearInterval(t);
    }, [open]);

    // The popover grows leftwards from the button; a side panel needs the
    // room for both columns, or it folds underneath instead.
    React.useEffect(() => {
      if (!open) return;
      let side = !mobile;
      try {
        const rect = wrapRef.current?.getBoundingClientRect?.();
        if (side && rect) side = rect.right - (MAIN_W + EXT_W) >= 8;
      } catch { /* measure failed: keep the default */ }
      setLayout(side ? "side" : "stack");
    }, [open, mobile]);

    const openPopover = () => {
      setTimeValue(toDatetimeLocalValue(typeof core.defaultSendAt === "function" ? core.defaultSendAt() : Date.now() + 5 * 60_000));
      setError(null);
      setPickerOpen(false);
      setMsg(String(draft ?? ""));
      echoes.current = [];
      setOpen(true);
    };

    const pick = (next) => { setTimeValue(next); setError(null); };

    const submit = async () => {
      if (busy) return;
      const content = String(msg ?? "");
      if (!content.trim()) { setError("The message is empty — type what to send first"); return; }
      const at = parseLocal(timeValue);
      if (!Number.isFinite(at) || at <= Date.now()) { setError("The send time must be in the future"); return; }
      setBusy(true);
      setError(null);
      try {
        const payload = { content, sendAt: at, conversationId: props.sessionId };
        await core.scheduleMessage(payload);
        // sidebar panel has its own state: refresh it NOW (its 8s poll would
        // otherwise lag ~10s behind a fresh task)
        if (props.onTaskCreated) void props.onTaskCreated();
        // spec: turn the draft into a scheduled task and clear the box — never send now (no submit)
        if (props.inputActions && typeof props.inputActions.setDraft === "function") props.inputActions.setDraft("");
        setOpen(false);
      } catch (err) {
        // FIX 4 failure mode: nothing was enqueued — keep the popover open
        // with the form (time + draft) intact and surface the error.
        setError(String(err?.message || err));
      } finally {
        setBusy(false);
      }
    };

    const btnStyle = {
      cursor: "pointer", flexShrink: 0, border: "1px solid " + (open ? "#3b82f6" : "transparent"),
      background: open ? "rgba(59,130,246,.12)" : "transparent",
      color: open ? "#3b82f6" : "inherit",
      borderRadius: 999, fontSize: 12, fontWeight: 600, lineHeight: "18px", padding: "1px 8px",
      display: "inline-flex", alignItems: "center", gap: 5,
      opacity: open ? 1 : 0.8,
      ...(mobile ? { minHeight: TOUCH_MIN } : {}),
    };
    const isDark = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    const side = layout === "side";
    const muted = isDark ? "rgba(255,255,255,.6)" : "rgba(0,0,0,.55)";
    const hairline = isDark ? "rgba(255,255,255,.14)" : "rgba(0,0,0,.10)";
    const field = isDark ? "rgba(255,255,255,.2)" : "rgba(0,0,0,.18)";
    // FIX 5: on ≤480px the popover spans (nearly) the full viewport width.
    const shell = {
      position: "absolute", bottom: "100%", right: 0, marginBottom: 6, zIndex: 30,
      width: side ? MAIN_W + EXT_W : MAIN_W, maxWidth: "calc(100vw - 16px)", boxSizing: "border-box",
      display: "flex", flexDirection: "column", overflow: "hidden", fontSize: 12,
      borderRadius: 14, border: "1px solid " + hairline,
      background: isDark ? "#1c1c1e" : "#fff",
      boxShadow: "0 12px 32px rgba(0,0,0,.28)",
      color: isDark ? "#eee" : "#111",
      ...(mobile ? { left: 0, right: 0, width: "calc(100vw - 16px)", maxHeight: "calc(100vh - 120px)", overflowY: "auto" } : {}),
    };
    const actionBtn = (extra) => ({
      cursor: "pointer", borderRadius: 999, padding: "5px 16px", fontSize: 12, ...(extra || {}),
      ...(mobile ? { minHeight: TOUCH_MIN, boxSizing: "border-box" } : {}),
    });

    const at = parseLocal(timeValue);
    const valid = Number.isFinite(at);
    const past = valid && at <= now;
    const when = valid ? new Date(at) : null;
    const parts = when ? clock12(when) : null;
    const day = when ? isDaytime(hourOf(when)) : true;
    const chosenKey = presetsFor(now).find((p) => valid && Math.abs(p.at - at) < 60_000)?.key;

    const readout = h("div", { key: "read", style: { display: "flex", alignItems: "center", gap: 12 } }, [
      h(TimeDial, { key: "dial", ms: at, isDark, size: side ? 124 : 104 }),
      h("div", { key: "txt", style: { display: "flex", flexDirection: "column", gap: 4, minWidth: 0 } }, [
        parts
          ? h("div", { key: "big", style: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } }, [
              h("span", { key: "hm", style: { fontSize: 30, fontWeight: 700, lineHeight: "32px", fontVariantNumeric: "tabular-nums", letterSpacing: "-.5px" } },
                parts.h12 + ":" + parts.mm),
              h("span", {
                key: "ap",
                title: day ? "Daytime" : "Night-time",
                style: {
                  display: "inline-flex", alignItems: "center", gap: 4, padding: "2px 8px", borderRadius: 999,
                  fontSize: 11, fontWeight: 700, letterSpacing: ".5px",
                  background: day ? "rgba(251,191,36,.18)" : "rgba(99,102,241,.22)",
                  color: day ? (isDark ? "#fcd34d" : "#b45309") : (isDark ? "#c7d2fe" : "#4338ca"),
                  transition: "background .4s, color .4s",
                },
              }, [day ? SunGlyph(12) : MoonGlyph(12), h("span", { key: "t" }, parts.ampm)]),
            ])
          : h("div", { key: "big", style: { fontSize: 14, color: muted } }, "Pick a time"),
        when ? h("div", { key: "day", style: { color: muted } }, dayLine(at, now)) : null,
        when
          ? h("div", {
              key: "in",
              style: { display: "inline-flex", alignItems: "center", gap: 5, fontWeight: 600, color: past ? "#dc2626" : "#3b82f6" },
            }, past
              ? "That time has already passed"
              : [HourglassIcon(12), h("span", { key: "t" }, sendsIn(at, now))])
          : null,
      ]),
    ]);

    const chips = h("div", { key: "chips", style: { display: "flex", flexWrap: "wrap", gap: 6 } },
      presetsFor(now).map((p) => h("button", {
        key: p.key, type: "button", className: "dsl-chip",
        onClick: () => pick(toDatetimeLocalValue(p.at)),
        style: {
          cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 5,
          borderRadius: 999, padding: "3px 10px", fontSize: 11, fontWeight: 600,
          border: "1px solid " + (chosenKey === p.key ? "#3b82f6" : field),
          background: chosenKey === p.key ? "rgba(59,130,246,.14)" : "transparent",
          color: chosenKey === p.key ? "#3b82f6" : "inherit",
          ...(mobile ? { minHeight: TOUCH_MIN, boxSizing: "border-box" } : {}),
        },
      }, [
        p.day ? SunGlyph(11, "#f59e0b") : p.night ? MoonGlyph(11, "#818cf8") : null,
        h("span", { key: "l" }, p.label),
      ])));

    const editor = h("div", {
      key: "msg", style: { display: "flex", flexDirection: "column", gap: 4, flex: side ? 1 : "none", minHeight: 0 },
    }, [
      h("div", { key: "l", style: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 11, color: muted } }, [
        h("span", { key: "a" }, "Message"),
        canSync ? h("span", { key: "b", style: { marginLeft: "auto", fontSize: 10 } }, "same as the message box") : null,
      ]),
      h("textarea", {
        key: "t", value: msg, rows: side ? 5 : 3, "aria-label": "Message to send later",
        placeholder: "Type what to send later…",
        autoFocus: !String(msg).trim(),
        onChange: (e) => editMsg(e?.target?.value ?? ""),
        onKeyDown: (e) => {
          if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) { e.preventDefault?.(); void submit(); }
        },
        style: {
          flex: side ? 1 : "none", minHeight: side ? 96 : 64, width: "100%", boxSizing: "border-box",
          resize: side ? "none" : "vertical", fontFamily: "inherit", fontSize: mobile ? 16 : 12, lineHeight: "17px",
          padding: "7px 9px", borderRadius: 8, border: "1px solid " + field, outline: "none",
          background: isDark ? "rgba(255,255,255,.05)" : "#fff", color: "inherit",
        },
      }),
      h("span", { key: "k", style: { fontSize: 10, color: muted } }, "Ctrl+Enter to confirm"),
    ]);

    const pickerToggle = side
      ? null
      : h("button", {
          key: "pt", type: "button", "aria-expanded": pickerOpen, onClick: () => setPickerOpen(!pickerOpen),
          style: {
            cursor: "pointer", display: "flex", alignItems: "center", gap: 6, width: "100%", boxSizing: "border-box",
            border: "1px solid " + field, borderRadius: 8, padding: "6px 10px", fontSize: 12, fontWeight: 600,
            background: "transparent", color: "inherit",
            ...(mobile ? { minHeight: TOUCH_MIN } : {}),
          },
        }, [
          h("span", { key: "l" }, "Change date & time"),
          h("span", { key: "c", style: { marginLeft: "auto", opacity: 0.6 } }, pickerOpen ? "▴" : "▾"),
        ]);

    const actions = h("div", { key: "act", style: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginTop: side ? "auto" : 0 } }, [
      h("button", {
        key: "ok", type: "button", disabled: busy, onClick: submit,
        style: actionBtn({ border: "none", fontWeight: 600, color: "#fff", background: "#3b82f6", opacity: busy ? .6 : 1, cursor: busy ? "wait" : "pointer" }),
      }, busy ? "Scheduling…" : "Confirm"),
      h("button", {
        key: "no", type: "button", onClick: () => setOpen(false),
        style: actionBtn({ border: "1px solid " + field, background: "transparent", color: "inherit", cursor: "pointer" }),
      }, "Cancel"),
      error ? h("span", { key: "e", style: { color: "#dc2626", wordBreak: "break-word" } }, error) : null,
    ]);

    const main = h("div", {
      key: "main",
      style: { width: side ? MAIN_W : "auto", boxSizing: "border-box", padding: "12px 14px 14px", display: "flex", flexDirection: "column", gap: 12 },
    }, [readout, chips, editor, pickerToggle, actions]);

    const extension = side || pickerOpen
      ? h("div", {
          key: "ext",
          style: {
            width: side ? EXT_W : "auto", boxSizing: "border-box", padding: "12px 14px 14px",
            borderLeft: side ? "1px solid " + hairline : "none", borderTop: side ? "none" : "1px solid " + hairline,
            background: isDark ? "rgba(255,255,255,.025)" : "rgba(0,0,0,.018)",
          },
        }, h(DateTimePanel, { value: timeValue, onChange: pick, now, isDark, mobile, muted, hairline }))
      : null;

    return h("div", { ref: wrapRef, "data-plugin": "dsh-schedule-later-button", style: { position: "relative", display: "inline-flex", alignItems: "center", gap: 6 } }, [
      open
        ? h("span", { key: "badge", style: { flexShrink: 0 } },
            h("span", { style: {
              display: "inline-flex", alignItems: "center", gap: 5, borderRadius: 999,
              padding: "1px 8px", fontSize: 11, fontWeight: 700,
              background: "rgba(59,130,246,.16)", color: "#3b82f6",
            } }, [HourglassIcon(12), h("span", { key: "t" }, "Scheduling…")]))
        : null,
      h("button", {
        key: "alarm", type: "button", className: "dsl-btn", onClick: open ? () => setOpen(false) : openPopover,
        title: "Schedule send", "aria-label": "Schedule send", "aria-expanded": open, style: btnStyle,
      }, [StopwatchIcon(14, open ? "spin" : ""), h("span", { key: "l" }, "Schedule")]),
      open
        ? h("div", {
            key: "pop", className: "dsl-pop dsl-motion", style: shell, role: "dialog", "aria-label": "Schedule send",
            "data-send-at": timeValue, "data-layout": layout,
            onKeyDown: (e) => { if (e.key === "Escape") setOpen(false); },
          }, [
            h(SkyBand, { key: "sky", ms: at, title: "Schedule send" }),
            h("div", { key: "body", style: { display: "flex", flexDirection: side ? "row" : "column", alignItems: "stretch" } }, [main, extension]),
          ])
        : null,
    ]);
  }

  /* --- pending-task dock (conversation.input.dock) ---------------------- */
  function ScheduledDock(props) {
    const core = props.core;
    const [, setTick] = React.useState(0);
    // FIX 2: tri-state user override — null = default policy, 'expanded',
    // 'collapsed' (manual collapse-all works for ANY count).
    const [user, setUser] = React.useState(null);
    const mobile = isMobile();

    // FIX 1: react to sessionId changes — bind the core to the NEW session
    // and refresh IMMEDIATELY (no waiting for the next poll tick).
    React.useEffect(() => {
      let stopped = false;
      let timer = null;
      core.setSession(props.sessionId);
      const loop = async () => {
        if (stopped) return;
        await core.refresh().catch(() => {});
        if (!stopped) setTick((n) => n + 1);
        if (!stopped) { timer = setTimeout(loop, 3000); timer.unref?.(); }
      };
      void loop();
      return () => {
        stopped = true;
        clearTimeout(timer);
      };
    }, [props.sessionId]);
    // countdown ticker
    React.useEffect(() => {
      const t = setInterval(() => setTick((n) => n + 1), 1000);
      t.unref?.(); // never hold the host loop for a UI countdown
      return () => clearInterval(t);
    }, []);

    const tasks = core.visibleTasks();
    const err = core.lastError();
    const st = collapseState(tasks, { user, mobile });
    const isDark = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    const now = Date.now();
    ensureStyles();
    const visible = tasks.slice(0, st.visibleCount);
    const showToggle = tasks.length > 0;
    if (!tasks.length && !err) return null;

    const rowStyle = {
      display: "flex", flexDirection: "column", gap: 2, width: "100%", maxWidth: "48rem",
      margin: "2px auto 0", fontSize: 12, lineHeight: "18px",
      boxSizing: "border-box",
    };
    const entryStyle = {
      display: "flex", flexDirection: "column", gap: 2, padding: "4px 8px", borderRadius: 8,
      background: "rgba(59,130,246,.10)", border: "1px solid rgba(59,130,246,.22)",
      maxWidth: "100%", width: "100%", boxSizing: "border-box", overflowWrap: "break-word",
    };
    const srcStyle = {
      margin: 0, whiteSpace: "pre-wrap", fontFamily: "monospace", fontSize: 12,
      wordBreak: "break-word", maxWidth: "100%",
    };
    const metaStyle = { display: "flex", alignItems: "center", gap: 8, color: "rgba(128,128,128,1)", flexWrap: "wrap", maxWidth: "100%" };
    const cancelBtn = (id) => h("button", {
      key: "x", type: "button", onClick: () => { core.cancelTask(id); },
      style: {
        cursor: "pointer", border: "1px solid rgba(128,128,128,.4)", borderRadius: 999, padding: "0 8px",
        fontSize: 11, background: "transparent", color: "inherit", flexShrink: 0,
        ...(mobile ? { minHeight: TOUCH_MIN } : {}),
      },
    }, "Cancel");

    return h("div", { "data-plugin": "dsh-schedule-later-dock", style: rowStyle }, [
      err
        ? h("div", {
            key: "err",
            style: { padding: "3px 8px", borderRadius: 8, background: "rgba(220,38,38,.10)", color: "#dc2626", wordBreak: "break-word" },
          }, "⚠ Could not refresh — showing the last list: " + err)
        : null,
      showToggle && st.summary
        ? h("button", {
            key: "sum", type: "button",
            onClick: () => { setUser(st.display === "expanded" ? "collapsed" : "expanded"); setTick((n) => n + 1); },
            style: {
              cursor: "pointer", alignSelf: "center", border: "1px solid rgba(59,130,246,.35)", borderRadius: 999,
              padding: "1px 10px", fontSize: 11, fontWeight: 600, background: "rgba(59,130,246,.10)", color: "inherit",
              ...(mobile ? { minHeight: TOUCH_MIN, boxSizing: "border-box" } : {}),
            },
          }, st.summary)
        : null,
      // The entries scroll inside a capped box, so an expanded list of long
      // messages never grows past the toggle above it: "Collapse ⌃" stays on
      // screen however many are pending.
      visible.length
        ? h("div", {
            key: "list", className: "dsl-dock-list", "data-plugin": "dsh-schedule-later-dock-list",
            style: {
              display: "flex", flexDirection: "column", gap: 2, width: "100%",
              maxHeight: mobile ? "40vh" : "min(40vh, 320px)", overflowY: "auto", overscrollBehavior: "contain",
            },
          }, visible.map((t) => {
            const sky = skyRow(t.sendAt, now);
            return h("div", { key: t.id, className: sky.className, style: { ...entryStyle, ...sky.style, flex: "none" } }, [
              h("div", { key: "src", style: srcStyle }, t.content),
              h("div", { key: "meta", style: metaStyle }, [
                whenPill(t.sendAt, now, isDark),
                h("span", { key: "cd" }, sendsIn(t.sendAt, now)),
                h("span", { key: "sp", style: { marginLeft: "auto" } }, cancelBtn(t.id)),
              ]),
            ]);
          }))
        : null,
    ]);
  }

  /* --- sidebar footer "Scheduled" panel (0.3.0) ------------------------------- */
  function ScheduledTasksPanel(props) {
    const core = props.panelCore;
    const [open, setOpen] = React.useState(false);
    const [tick, setTick] = React.useState(0);
    const [hover, setHover] = React.useState(false);
    const mobile = isMobile();
    ensureStyles();

    // keep the badge alive even while the panel is closed: poll the FULL
    // (unfiltered) state — every conversation's pending tasks, 8s cadence.
    React.useEffect(() => {
      let stopped = false;
      let timer = null;
      const loop = async () => {
        if (stopped) return;
        await core.refresh().catch(() => {});
        if (!stopped) setTick((n) => n + 1);
        if (!stopped) { timer = setTimeout(loop, 8000); timer.unref?.(); }
      };
      void loop();
      return () => { stopped = true; clearTimeout(timer); };
    }, []);

    const all = core.visibleTasks(); // ALL sessions, sendAt ascending
    const err = core.lastError();
    const MAX_ROWS = 100;
    const annotated = annotateSessions(all.slice(0, MAX_ROWS), props.sessionById ? props.sessionById() : null);
    const overflow = Math.max(0, all.length - annotated.length);

    const isDark = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    // mirrors usage-stats' footer trigger: same metrics + theme variables as
    // the system sidebar rows (hover comes from the injected var-only rule)
    const layerStyle = {
      flex: "0 0 100%", minWidth: 0, alignItems: "center", height: 49,
      margin: "8px 0 0", display: "flex", position: "relative",
    };
    const entryBtn = {
      width: "100%", minWidth: 0, height: 49, color: "var(--dsw-alias-label-primary)",
      cursor: "pointer", background: "0 0", border: "none", borderRadius: 12,
      alignItems: "center", gap: 8, padding: "0 8px 0 6px", fontFamily: "inherit",
      fontSize: 14, display: "inline-flex", overflow: "hidden",
    };
    const iconBox = { display: "inline-flex", alignItems: "center", flex: "none" };

    const labelStyle = { textOverflow: "ellipsis", whiteSpace: "nowrap", minWidth: 0, overflow: "hidden" };
    const amountStyle = {
      color: "var(--dsw-alias-label-secondary)", fontVariantNumeric: "tabular-nums",
      flex: "none", fontSize: 12, fontWeight: 600, lineHeight: "16px",
    };
    const countStyle = {
      color: "var(--dsw-alias-label-tertiary)", fontVariantNumeric: "tabular-nums",
      flex: "none", marginLeft: "auto", fontSize: 12, lineHeight: "16px",
    };
    const badge = (n) => h("span", {
      key: "b", "data-badge": n,
      style: {
        display: "inline-flex", alignItems: "center", justifyContent: "center",
        minWidth: 16, height: 16, padding: "0 4px", borderRadius: 999,
        background: "#3b82f6", color: "#fff", fontSize: 10, fontWeight: 700,
      },
    }, String(n));

    const jump = (t) => {
      // failure mode: jump unavailable/unknown session → keep the panel open,
      // keep the row (still cancellable); never throw into the click handler.
      const ok = props.openSession ? props.openSession(t.conversationId) : false;
      if (ok) setOpen(false);
    };
    const cancelBtn = (t) => h("button", {
      key: "x", type: "button",
      onClick: (e) => {
        if (e && typeof e.stopPropagation === "function") e.stopPropagation();
        core.cancelTask(t.id).catch(() => {});
        setTick((n) => n + 1);
      },
      style: {
        cursor: "pointer", border: "1px solid rgba(128,128,128,.4)", borderRadius: 999,
        padding: "0 8px", fontSize: 11, background: "transparent", color: "inherit", flexShrink: 0,
        ...(mobile ? { minHeight: TOUCH_MIN, boxSizing: "border-box" } : {}),
      },
    }, "Cancel");

    const footer = open
      ? h("div", {
          key: "panel", "data-plugin": "dsh-schedule-later-sidebar-panel",
          style: {
            position: "fixed", bottom: 56, left: 12, zIndex: 50,
            width: 340, maxWidth: "calc(100vw - 24px)", maxHeight: "70vh", overflowY: "auto",
            boxSizing: "border-box", padding: "10px 12px", fontSize: 12,
            borderRadius: 12, border: "1px solid " + (isDark ? "rgba(255,255,255,.14)" : "rgba(0,0,0,.10)"),
            background: isDark ? "#1c1c1e" : "#fff",
            boxShadow: "0 8px 24px rgba(0,0,0,.18)",
            color: isDark ? "#eee" : "#111",
            ...(mobile ? { left: 8, width: "calc(100vw - 16px)", maxWidth: "calc(100vw - 16px)" } : {}),
          },
        }, [
          h("div", {
            key: "head", style: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 },
          }, [
            h("span", { key: "t", style: { fontWeight: 700, fontSize: 13, display: "inline-flex", alignItems: "center", gap: 6 } }, [StopwatchIcon(14), h("span", { key: "l" }, "Scheduled")]),
            h("span", { key: "n", style: { opacity: .6 } }, all.length ? `${all.length} pending` : ""),
            h("button", {
              key: "close", type: "button", onClick: () => setOpen(false),
              style: { cursor: "pointer", marginLeft: "auto", border: "none", background: "transparent", color: "inherit", fontSize: 14, lineHeight: 1 },
            }, "✕"),
          ]),
          err
            ? h("div", {
                key: "err",
                style: { padding: "3px 8px", borderRadius: 8, background: "rgba(220,38,38,.10)", color: "#dc2626", wordBreak: "break-word" },
              }, "⚠ Could not refresh — showing the last list: " + err)
            : null,
          !all.length && !err
            ? h("div", { key: "empty", style: { padding: "18px 0", textAlign: "center", opacity: .6 } }, [
                h("div", { key: "l1" }, "No scheduled messages"),
                h("div", { key: "l2", style: { marginTop: 4 } }, "Click Schedule in a chat's message box to create one"),
              ])
            : null,
          annotated.map((t) => h("div", {
            key: t.id, "data-task": t.id, className: skyRow(t.sendAt, Date.now()).className,
            onClick: () => { if (t.sessionExists) jump(t); },
            title: t.sessionExists ? "Open this chat" : "Chat no longer exists — can only be cancelled",
            style: {
              display: "flex", flexDirection: "column", gap: 2, padding: "6px 8px", marginBottom: 4,
              borderRadius: 8, ...skyRow(t.sendAt, Date.now()).style,
              cursor: t.sessionExists ? "pointer" : "default",
              opacity: t.sessionExists ? 1 : 0.5,
              wordBreak: "break-word", maxWidth: "100%", boxSizing: "border-box",
            },
          }, [
            h("div", { key: "c", style: { whiteSpace: "pre-wrap", fontFamily: "monospace" } },
              summarizeContent(t.content) || "(empty)"),
            h("div", { key: "m", style: { display: "flex", alignItems: "center", gap: 8, color: "rgba(128,128,128,1)" } }, [
              h("span", { key: "s", style: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } },
                t.sessionExists ? t.sessionTitle : "Chat no longer exists"),
              whenPill(t.sendAt, Date.now(), isDark),
            ]),
            h("div", { key: "act", style: { display: "flex", alignItems: "center", gap: 8 } }, [
              h("span", { key: "cd", style: { color: "#3b82f6", fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 5 } },
                [HourglassIcon(11), h("span", { key: "t" }, sendsIn(t.sendAt, Date.now()))]),
              h("span", { key: "sp", style: { marginLeft: "auto" } }, cancelBtn(t)),
            ]),
          ])),
          overflow > 0
            ? h("div", { key: "more", style: { textAlign: "center", opacity: .6, padding: "4px 0" } },
                `Showing the next ${annotated.length} of ${all.length}`)
            : null,
        ])
      : null;

    return h("div", { "data-plugin": "dsh-schedule-later-sidebar", style: layerStyle }, [
      h("style", { key: "css" }, '.ssb_badge:hover{background:var(--dsw-alias-interactive-bg-hover-solid)}'),
      h("button", {
        key: "btn", type: "button",
        className: "ssb_badge",
        onClick: () => { setOpen(!open); setTick((n) => n + 1); },
        title: "Scheduled messages", "aria-label": "Scheduled messages", style: entryBtn,
      }, [
        // ticks slowly while anything is waiting to be sent
        h("span", { key: "i", style: iconBox }, StopwatchIcon(16, all.length ? "slow" : "")),
        h("span", { key: "l", style: labelStyle }, "Scheduled"),
        all.length ? badge(all.length) : null,
      ]),
      footer,
    ]);
  }

  /** Client plugin body. Returns the cordis plugin ({inject, apply}). */
  return function buildPlugin({ stateRoutePath, fetchImpl }) {
    const schedulePath = stateRoutePath.replace(/\/state$/, "/schedule");
    const doFetch = fetchImpl || ((...a) => fetch(...a));

    let currentSessionId = null;

    const doCancel = async (id) => {
      const res = await doFetch(schedulePath + "?id=" + encodeURIComponent(id), { method: "DELETE" });
      return res.ok;
    };

    // 0.3.0 panel core: UNBOUND (session null) — fetches the FULL task list
    // (no conversationId filter) for the sidebar badge + panel; cancel reuses
    // the same DELETE route (cross-conversation).
    const panelCore = createScheduledClientState({
      fetchState: async () => {
        const res = await doFetch(stateRoutePath, { headers: { accept: "application/json" } });
    // cross-instance sync: a cancel/create in either surface refreshes the
    // other immediately (no 4s poll lag)
    core.onChanged = (id) => { if (id) panelCore.removeTask(id); void panelCore.refresh(); };
    panelCore.onChanged = () => { void core.refresh(); };
        if (!res.ok) throw new Error("state HTTP " + res.status);
        return res.json();
      },
      cancelSchedule: doCancel,
    });
    panelCore.setSession(null);

    const core = createScheduledClientState({
      fetchState: async () => {
        // ask the host for THIS conversation's view (the core's bound session
        // is authoritative — the view binds it before every refresh); the
        // core still filters strictly client-side against stale caches.
        const sid = core.currentSession();
        const q = sid ? "?conversationId=" + encodeURIComponent(sid) : "";
        const res = await doFetch(stateRoutePath + q, { headers: { accept: "application/json" } });
        if (!res.ok) throw new Error("state HTTP " + res.status);
        return res.json();
      },
      postSchedule: async (payload) => {
        const res = await doFetch(schedulePath, {
          method: "POST", headers: { "content-type": "application/json", accept: "application/json" },
          body: JSON.stringify(payload),
        });
        const body = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(body.error || ("HTTP " + res.status));
        return body;
      },
      cancelSchedule: async (id) => {
        const res = await doFetch(schedulePath + "?id=" + encodeURIComponent(id), { method: "DELETE" });
        return res.ok;
      },
    });
    core.defaultSendAt = () => defaultSendAt();

    const inject = ["slots", "sessions"]; // sessions: sidebar panel jump (0.3.0)
    function apply(ctx) {
      // due-time delivery: refresh the sidebar panel the moment a task fires
      ctx.on?.('guard/scheduled-due', () => { void panelCore.refresh(); });
      ctx.on?.('guard/scheduled-dropped', () => { void panelCore.refresh(); });
      ctx.inject(inject, (scope) => {
        // 0.3.0 session navigation, sourced from the sessions service:
        //  - open(id) selects a session as current (unknown ids throw → false)
        //  - list.getSnapshot().byId maps id → {displayTitle} for row labels
        const svc = scope.sessions;
        const openSession = (sid) => {
          try {
            if (svc && typeof svc.open === "function" && sid) { svc.open(sid); return true; }
          } catch (err) { /* unknown session — degrade, row stays cancellable */ }
          return false;
        };
        const sessionById = () => {
          try { return (svc && svc.list && svc.list.getSnapshot && svc.list.getSnapshot().byId) || {}; }
          catch (err) { return {}; }
        };
        scope.slots.inject("sidebar.footer.action", () => scope.slots.register({
          name: "sidebar.footer.action",
          id: "dsh-schedule-later",
          order: 20,
        }, (slotProps) => ScheduledTasksPanel({ ...(slotProps || {}), panelCore, openSession, sessionById })));
        scope.slots.inject("conversation.input.right", () => scope.slots.register({
          name: "conversation.input.right",
          id: "dsh-schedule-later",
          order: 100,
          inject: (sessionId) => {
            currentSessionId = sessionId;
            core.setSession(sessionId); // dock/button are conversation-scoped
            return { sessionId, core, onTaskCreated: () => panelCore.refresh() };
          },
        }, ScheduleButton));
        scope.slots.inject("conversation.input.dock", () => scope.slots.register({
          name: "conversation.input.dock",
          id: "dsh-schedule-later",
          // The dock stacks by order, top to bottom: dsh's To-dos are 0, the
          // goal 10, the queue 20. Above all of them, so the To-dos stay
          // next to the message box.
          order: -10,
          inject: (sessionId) => {
            currentSessionId = sessionId;
            core.setSession(sessionId);
            return { sessionId, core, onTaskCreated: () => panelCore.refresh() };
          },
        }, ScheduledDock));
      });
    }
    return { core, inject, apply };
  };
}

		var built = createClientPluginBody(react)(/* config */ {
			stateRoutePath: "/plugin-data/dsh-schedule-later/state",
		});
		exports.core = built.core;
		exports.apply = built.apply;
		exports.inject = built.inject;
		return module.exports;
	}
});
