// Build script: generates lib/client.js — the dsh.client web bundle.
// Concatenates src/client-core.js + src/client-view.js into a
// window.__ModuleLoader__.load({id, factory}) CJS-style factory, which is the
// bundle form DSH client plugins ship (see dsh-client-modules README).
// Usage: node scripts/build-client.mjs
import { fs } from '../src/deps.js';

const read = (p) => fs.readFile(new URL(p, import.meta.url), 'utf8');

const core = await read('../src/client-core.js');
const view = await read('../src/client-view.js');
const strip = (s) => s.replace(/^export (function|const|class)/gm, '$1');

const bundle = `// GENERATED by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
	id: "dsh-schedule-later",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		var react = require("react");
		var react_jsx_runtime = react;
${strip(core)}
${strip(view)}
		var built = createClientPluginBody(react)(/* config */ {
			stateRoutePath: "/plugin-data/dsh-schedule-later/state",
		});
		exports.core = built.core;
		exports.apply = built.apply;
		exports.inject = built.inject;
		return module.exports;
	}
});
`;

const out = new URL('../lib/client.js', import.meta.url);
await fs.mkdir(new URL('../lib/', import.meta.url), { recursive: true });
await fs.writeFile(out, bundle, 'utf8');
console.log('wrote lib/client.js', bundle.length, 'bytes');
